### ISSUE TITLE
Add React Deployment dockefile

### ISSUE THREAD

**Issue by darkmatter18** [darkmatter18/dockerfile-archive#5]
The task is as follows:

1. Create a directory as `javascript` under `dockerfiles/deployment`
2. Create a directory inside `javascript` as the name of your approach like: `react_with_nginx`. Full path `dockerfiles/deployment/javascript/react_with_nginx`
3. Add all required files including the dockerfile inside the directory.
4. Add a `README.md` inside that directory as a little documentation and steps

**Comment by RohitShah1706** [comment]
@darkmatter18 Please assign this issue to me.
I have a keen interest in Docker and kubernetes.

**Comment by darkmatter18** [comment]
@RohitShah1706 That's great. Please add some more issues as well, so that others can also work.

**Comment by RohitShah1706** [comment]
Yeah sure, I have some redis and nginx dockerfiles.

**Comment by RohitShah1706** [comment]
@darkmatter18 
Just wanted to know, is this repo under hacktoberfest 22.

**Comment by Shivansh-Mittal** [comment]
@darkmatter18 
You can check the PR for this feature need.
