### ISSUE TITLE
Add Express Js Deployment Dockerfile

### ISSUE THREAD

**Issue by darkmatter18** [darkmatter18/dockerfile-archive#6]
The task is as follows:

1. Create a directory as `javascript` under `dockerfiles/deployment`
2. Create a directory inside `react` as the name of your approach like: `express_with_nginx`. Full path `dockerfiles/deployment/javascript/express_with_nginx`
3. Add all required files including the dockerfile inside the directory.
4. Add a `README.md` inside that directory as a little documentation and steps

**Comment by RohitShah1706** [comment]
@darkmatter18 I would like to solve this issue.
Please assign this to me.

**Comment by darkmatter18** [comment]
@RohitShah1706 Assigned, go for it

**Comment by Tweniee** [comment]
@darkmatter18 can i work on this, if yes 

then is this only Javascript only for express of 
need to create dockerfile for express in typescript?

**Comment by neelbhanushali** [comment]
@darkmatter18 

Kindly close if this is complete
It is showing on up-for-grabs.net
