### ISSUE TITLE
Add Next Js Deployment dockerfile

### ISSUE THREAD

**Issue by darkmatter18** [darkmatter18/dockerfile-archive#7]
The task is as follows:

1. Create a directory as `javascript` under `dockerfiles/deployment`
2. Create a directory inside `javascript` as the name of your approach like: `next_with_nginx`. Full path `dockerfiles/deployment/javascript/next_with_nginx`
3. Add all required files including the dockerfile inside the directory.
4. Add a `README.md` inside that directory as a little documentation and steps

**Comment by ssghait007** [comment]
@darkmatter18 I can take this up

**Comment by darkmatter18** [comment]
@ssghait007 Sure. Assigning to you

**Comment by FrankV01** [comment]
This appears done.  🥇
